#!/bin/bash
# mobilevis-restore
# Shell script that takes a timestamp of a backup which is available on S3, downloads the backup,
# decrypts it, and restores it. This should be re-written to be more general in the future
#   example : mobilevis-restore 201412234212 full
#             mobilevis-restire base

chmod 777 /vagrant/deploy/shared/backup/mobilevis-restore
/vagrant/deploy/shared/backup/mobilevis-restore "$@" db-backups-dev