# Provision server. This playbook must be run when a server is first created
# and is typically only run once. It may be run again if you make server-level
# changes or need to update any installed apt modules to their latest versions.

- hosts: all
  become: yes
  become_method: sudo
  vars:
    commit: master
    force: false
  roles:
    - base
    - configure
    - deploy
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart postgresql
      service: name=postgresql state=restarted

    - name: restart mobilevis
      service: name=mobilevis state=restarted
