#
# apt installs
#

# Can't use ansible's apt_repository module because we need to fetch gpg keys
# that are hosted on SNI-enabled servers. Python doesn't support SNI natively
# until 2.7.9 and ubuntu 14.04 ships with 2.7.6. Updating the system python is
# not a road we'll be going down.
- name: add keys to apt
  shell: wget -qO - {{item}} | apt-key add -
  with_items: "{{ apt_keys }}"
# If you are running this on a system with python 2.7.9+, use this instead
#- name: add keys to apt
#  apt_key: url={{item}} state=present
#  with_items: apt_keys

- name: add ppas to apt
  apt_repository: repo="{{item}}" update_cache=yes
  with_items: "{{apt_ppas}}"

- name: install apt packages
  apt: name={{item}} state=latest update_cache=yes
  with_items: "{{apt_packages}}"

- name: postgresql is installed
  apt: name=postgresql state=present
  environment:
    LC_ALL: en_US.UTF-8
  tags:
    - postgres

- name: postgresql contrib extensions are installed
  apt: name=postgresql-contrib state=present