#! /bin/sh
# This script is responsible for updating the mobilevis app source in
# production. This involves:
#   checking out updates from git
#   running npm install & bower install
#   grunt build
#   restart mobilevis app
# TODO: figure out how to run migrations?

cd /vagrant

# reset to recent head, so we don't have to deal with checkout conflicts.
git reset --hard
git pull origin master

# reset permissions on executables
chmod 777 /vagrant/deploy/prod/backup/mobilevis-backup
chmod 777 /vagrant/deploy/prod/backup/mobilevis-restore
chmod 777 /vagrant/deploy/shared/backup/mobilevis-backup
chmod 777 /vagrant/deploy/shared/backup/mobilevis-restore
chmod 777 /vagrant/deploy/prod/source/update-source

npm install
bower install
grunt build
sudo forever restartall
