#! /bin/sh
# This script is responsible for updating the mobilevis app source in
# production. This involves:
#   checking out updates from git
#   running npm install & bower install
#   grunt build
#   restart mobilevis app
# TODO: figure out how to run migrations?

cd /vagrant

# before we reset permissions, reown the files we had to set up for root
sudo chown ubuntu:ubuntu /vagrant/deploy/prod/logrotate/mobilevis

# reset to recent head, so we don't have to deal with checkout conflicts.
git reset --hard
git pull origin master

# reset permissions on executables
chmod 777 /vagrant/deploy/prod/backup/mobilevis-backup
chmod 777 /vagrant/deploy/prod/backup/mobilevis-restore
chmod 777 /vagrant/deploy/shared/backup/mobilevis-backup
chmod 777 /vagrant/deploy/shared/backup/mobilevis-restore
chmod 777 /vagrant/deploy/prod/source/update-source

# reset permissions to logrotate or it won't work anymore
sudo chown root:root /vagrant/deploy/prod/logrotate/mobilevis
sudo chmod 644 /vagrant/deploy/prod/logrotate/mobilevis

npm install
bower install
grunt build
sudo forever restartall
