#
# move backup and restore scripts to the correct places
# TO restore from latest:
# mobilevis-restore 201504271636 full db-backups
# TODO: write a proper script for that...
- name: copy backup and restore scripts
  template: src={{item}} dest=/usr/local/bin/{{item}} mode=755
  with_items: backup_scripts