# If defined, only this many of the most recent clone directories (including the
# current specified commit) will be retained. Anything older will be removed,
# once the current clone has been made live.
keep_n_most_recent: 3
backup_scripts:
  - mobilevis-backup
  - mobilevis-restore
config_files_remote:
  - { src: mobilevis.s3.js, dest: s3.js }
  - { src: mobilevis.twitter.js, dest: twitter.js }