#!/bin/bash
# mobilevis-restore
# Shell script that takes a timestamp of a backup which is available on S3, downloads the backup,
# decrypts it, and restores it. This should be re-written to be more general in the future
#

if [ "$#" -ne 1 ]
then
  echo "Available commands are:"
  echo "mobilevis-restore base - will restore base setup"
  echo "mobilevis-restore latest - will restore latest in s3"
  echo "mobilevis-restore 201404031353 - will restore specific dump"
  exit 1
fi

args=("$@");
folder={{backup_folder}}

WORKING_DIR={{base_path}}/

if [ $1 = "base" ]
then
  BACKUP_FILE_NAME=schema.sql

  # drop existing
  psql -U postgres -d postgres -c "DROP DATABASE IF EXISTS mobilevis"

  # setup new one
  psql -U postgres -d postgres < ${WORKING_DIR}deploy/shared/db/${BACKUP_FILE_NAME}

elif [ $1 = "latest" ]
then

  BACKUP_FILE_NAME=`aws s3api list-objects --bucket {{s3_bucket}} \
    --prefix {{backup_folder}}/ \
    | jq '.Contents | sort_by(.LastModified) \
    | reverse | .[1] | .Key' | tail -1 | sed 's/\"//g'`

  FILE_NAME=`aws s3api list-objects --bucket {{s3_bucket}} \
    --prefix {{backup_folder}}/ \
    | jq '.Contents | sort_by(.LastModified) \
    | reverse | .[1] | .Key | split("/")[1]' | tail -1 | sed 's/\"//g'`

  echo "Restoring ${FILE_NAME}"
  aws s3api get-object --bucket {{s3_bucket}} \
    --key ${BACKUP_FILE_NAME} ${WORKING_DIR}${FILE_NAME}

  # drop existing
  psql -U postgres -d postgres -c "DROP DATABASE IF EXISTS mobilevis"

  # load new one
  # cat ${WORKING_DIR}/schema.sql | psql -U postgres -d postgres
  # psql -U postgres -d postgres -f ${WORKING_DIR}${FILE_NAME}
  createdb -U postgres mobilevis
  pg_restore -U postgres -d mobilevis ${WORKING_DIR}${FILE_NAME}

  #cleanup
  rm ${WORKING_DIR}${FILE_NAME}

else

  timestamp=${args[0]}

  if [ $2 = "full" ]
  then
    BACKUP_FILE_NAME=mobilevis-backup-${timestamp}.sql.gz
  else
    BACKUP_FILE_NAME=mobilevis-backup-${timestamp}-data.sql.gz
  fi

  aws s3 cp s3://{{s3_bucket}}/${folder}/${BACKUP_FILE_NAME} ${WORKING_DIR}${BACKUP_FILE_NAME}

  # drop existing
  psql -U postgres -d postgres -c "DROP DATABASE IF EXISTS mobilevis"

  createdb -U postgres mobilevis

  #gunzip it
  pg_restore -U postgres -d mobilevis ${WORKING_DIR}${BACKUP_FILE_NAME}

  #cleanup
  rm ${WORKING_DIR}${BACKUP_FILE_NAME}
fi

